"""add feedback tables

Revision ID: add_feedback_tables
Revises: 9c3a6b2f4a1d
Create Date: 2026-03-06 00:49:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "add_feedback_tables"
down_revision: Union[str, None] = "9c3a6b2f4a1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("priority", sa.String(length=20), nullable=False, server_default="normal"),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedbacks_category"), "feedbacks", ["category"], unique=False)
    op.create_index(op.f("ix_feedbacks_created_at"), "feedbacks", ["created_at"], unique=False)
    op.create_index(op.f("ix_feedbacks_id"), "feedbacks", ["id"], unique=False)
    op.create_index(op.f("ix_feedbacks_priority"), "feedbacks", ["priority"], unique=False)
    op.create_index(op.f("ix_feedbacks_resolved_at"), "feedbacks", ["resolved_at"], unique=False)
    op.create_index(op.f("ix_feedbacks_status"), "feedbacks", ["status"], unique=False)
    op.create_index(op.f("ix_feedbacks_type"), "feedbacks", ["type"], unique=False)
    op.create_index(op.f("ix_feedbacks_user_id"), "feedbacks", ["user_id"], unique=False)

    op.create_table(
        "feedback_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feedback_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["feedback_id"], ["feedbacks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedback_comments_created_at"), "feedback_comments", ["created_at"], unique=False)
    op.create_index(op.f("ix_feedback_comments_feedback_id"), "feedback_comments", ["feedback_id"], unique=False)
    op.create_index(op.f("ix_feedback_comments_id"), "feedback_comments", ["id"], unique=False)
    op.create_index(op.f("ix_feedback_comments_is_internal"), "feedback_comments", ["is_internal"], unique=False)
    op.create_index(op.f("ix_feedback_comments_user_id"), "feedback_comments", ["user_id"], unique=False)

    # 插入反馈相关权限
    op.bulk_insert(
        sa.table(
            "permissions",
            sa.Column("id", sa.UUID()),
            sa.Column("name", sa.String(length=100)),
            sa.Column("code", sa.String(length=100)),
            sa.Column("description", sa.String(length=500)),
            sa.Column("created_at", sa.DateTime(timezone=True)),
            sa.Column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": "11111111-1111-1111-1111-111111111111",
                "name": "提交反馈",
                "code": "feedback:create",
                "description": "允许用户提交反馈",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
            {
                "id": "22222222-2222-2222-2222-222222222222",
                "name": "查看反馈",
                "code": "feedback:read",
                "description": "允许用户查看自己的反馈",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
            {
                "id": "33333333-3333-3333-3333-333333333333",
                "name": "查看所有反馈",
                "code": "feedback:read:all",
                "description": "允许管理员查看所有用户的反馈",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
            {
                "id": "44444444-4444-4444-4444-444444444444",
                "name": "更新反馈状态",
                "code": "feedback:update",
                "description": "允许管理员更新反馈状态",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
            {
                "id": "55555555-5555-5555-5555-555555555555",
                "name": "删除反馈",
                "code": "feedback:delete",
                "description": "允许管理员删除反馈",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
            {
                "id": "66666666-6666-6666-6666-666666666666",
                "name": "添加反馈评论",
                "code": "feedback:comment",
                "description": "允许用户和管理员添加反馈评论",
                "created_at": sa.func.now(),
                "updated_at": sa.func.now(),
            },
        ],
    )

    # 为admin角色添加所有反馈权限
    op.execute(
        """
        INSERT INTO role_permissions (id, role_id, permission_id, created_at)
        SELECT 
            gen_random_uuid(),
            r.id,
            p.id,
            NOW()
        FROM roles r
        CROSS JOIN permissions p
        WHERE r.code = 'admin' 
        AND p.code IN (
            'feedback:create',
            'feedback:read',
            'feedback:read:all',
            'feedback:update',
            'feedback:delete',
            'feedback:comment'
        )
        ON CONFLICT DO NOTHING
        """
    )

    # 为user角色添加基本反馈权限
    op.execute(
        """
        INSERT INTO role_permissions (id, role_id, permission_id, created_at)
        SELECT 
            gen_random_uuid(),
            r.id,
            p.id,
            NOW()
        FROM roles r
        CROSS JOIN permissions p
        WHERE r.code = 'user' 
        AND p.code IN (
            'feedback:create',
            'feedback:read',
            'feedback:comment'
        )
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    # 删除角色权限关联
    op.execute(
        """
        DELETE FROM role_permissions 
        WHERE permission_id IN (
            SELECT id FROM permissions 
            WHERE code LIKE 'feedback:%'
        )
        """
    )

    # 删除权限
    op.execute("DELETE FROM permissions WHERE code LIKE 'feedback:%'")

    op.drop_index(op.f("ix_feedback_comments_user_id"), table_name="feedback_comments")
    op.drop_index(op.f("ix_feedback_comments_is_internal"), table_name="feedback_comments")
    op.drop_index(op.f("ix_feedback_comments_id"), table_name="feedback_comments")
    op.drop_index(op.f("ix_feedback_comments_feedback_id"), table_name="feedback_comments")
    op.drop_index(op.f("ix_feedback_comments_created_at"), table_name="feedback_comments")
    op.drop_table("feedback_comments")

    op.drop_index(op.f("ix_feedbacks_user_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_type"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_status"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_resolved_at"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_priority"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_created_at"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_category"), table_name="feedbacks")
    op.drop_table("feedbacks")
    # ### end Alembic commands ###