"""add health_status to threads table

Revision ID: 11f67b831f1e
Revises: 20260325_000000
Create Date: 2026-03-27 09:43:40.345269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11f67b831f1e'
down_revision: Union[str, None] = '20260325_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_interaction_logs_endpoint'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_intent_type'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_status'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_thread_id'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_trace_id'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_turn_id'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_llm_interaction_logs_user_id'), table_name='llm_interaction_logs', if_exists=True)
    op.drop_table('llm_interaction_logs', if_exists=True)
    op.drop_index(op.f('ix_files_user_uploaded'), table_name='files', if_exists=True)
    op.add_column('threads', sa.Column('health_status', sa.String(length=20), nullable=False, server_default='normal'))
    op.drop_index(op.f('ix_threads_user_status_updated'), table_name='threads', if_exists=True)
    op.create_index(op.f('ix_threads_health_status'), 'threads', ['health_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_health_status'), table_name='threads')
    op.create_index(op.f('ix_threads_user_status_updated'), 'threads', ['user_id', 'status', sa.literal_column('updated_at DESC NULLS LAST')], unique=False)
    op.drop_column('threads', 'health_status')
    op.create_index(op.f('ix_files_user_uploaded'), 'files', ['user_id', sa.literal_column('uploaded_at DESC NULLS LAST')], unique=False)
    op.create_table('llm_interaction_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='主键'),
    sa.Column('trace_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='链路追踪ID，用于串联单次请求'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True, comment='触发请求的用户ID'),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的对话会话ID'),
    sa.Column('turn_id', sa.UUID(), autoincrement=False, nullable=True, comment='轮次ID'),
    sa.Column('intent_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='触发本次调用的意图（chat, processing, intent_recognition）'),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='实际调用的模型名称'),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='请求来源的API路由路径'),
    sa.Column('prompt_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='完整入参：包含 System Prompt, 历史上下文, 用户当前 Query 等的完整数组'),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='完整出参：大模型返回的原始 JSON 结构'),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='输入消耗的 Token 数'),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='输出消耗的 Token 数'),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='接口响应耗时(毫秒)'),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='状态（success, failed, timeout）'),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True, comment='如果调用失败，记录具体的异常堆栈'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True, comment='记录创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_interaction_logs_pkey'))
    )
    op.create_index(op.f('ix_llm_interaction_logs_user_id'), 'llm_interaction_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_turn_id'), 'llm_interaction_logs', ['turn_id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_trace_id'), 'llm_interaction_logs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_thread_id'), 'llm_interaction_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_status'), 'llm_interaction_logs', ['status'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_intent_type'), 'llm_interaction_logs', ['intent_type'], unique=False)
    op.create_index(op.f('ix_llm_interaction_logs_endpoint'), 'llm_interaction_logs', ['endpoint'], unique=False)
    # ### end Alembic commands ###
