"""add intent_type and response_text to thread_turns

Revision ID: 20260309_212929
Revises: 1b7e4c9f2d11
Create Date: 2026-03-09 21:29:29.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260309_212929'
down_revision: Union[str, None] = '1b7e4c9f2d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_turns', sa.Column('intent_type', sa.String(length=50), nullable=True))
    op.add_column('thread_turns', sa.Column('response_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_thread_turns_intent_type'), 'thread_turns', ['intent_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_turns_intent_type'), table_name='thread_turns')
    op.drop_column('thread_turns', 'response_text')
    op.drop_column('thread_turns', 'intent_type')
    # ### end Alembic commands ###