"""add admin query performance indexes

Revision ID: 20260325_000000
Revises: 20260310_051530
Create Date: 2026-03-25 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260325_000000'
down_revision: Union[str, None] = 'f984dc0862b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 复合索引: 优化 GET /threads 查询 (按用户过滤、状态筛选、更新时间排序)
    # 支持以下查询模式:
    # 1. WHERE user_id = ? AND status = ? ORDER BY updated_at DESC (管理员查看指定用户线程)
    # 2. WHERE status = ? ORDER BY updated_at DESC (管理员查看所有线程)
    # 3. WHERE user_id = ? ORDER BY updated_at DESC (按用户过滤)
    op.create_index(
        'ix_threads_user_status_updated',
        'threads',
        ['user_id', 'status', 'updated_at'],
        unique=False,
        postgresql_ops={'updated_at': 'DESC NULLS LAST'}  # 按降序排序优化
    )

    # 复合索引: 优化 GET /users/{user_id}/files 查询 (按用户过滤、上传时间排序)
    # 支持以下查询模式:
    # 1. WHERE user_id = ? ORDER BY uploaded_at DESC (管理员查看用户文件)
    op.create_index(
        'ix_files_user_uploaded',
        'files',
        ['user_id', 'uploaded_at'],
        unique=False,
        postgresql_ops={'uploaded_at': 'DESC NULLS LAST'}  # 按降序排序优化
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_user_uploaded', table_name='files')
    op.drop_index('ix_threads_user_status_updated', table_name='threads')
    # ### end Alembic commands ###