"""add context_snapshot and parent_turn_id to thread_turns

Revision ID: 20260310_051530
Revises: 20260309_212929
Create Date: 2026-03-10 05:15:30.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260310_051530'
down_revision: Union[str, None] = '20260309_212929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 context_snapshot 字段 (JSONB, nullable)
    op.add_column('thread_turns', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # 添加 parent_turn_id 字段 (UUID, nullable, 外键引用 thread_turns.id)
    op.add_column('thread_turns', sa.Column('parent_turn_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # 创建外键约束
    op.create_foreign_key(
        'fk_thread_turns_parent_turn_id',
        'thread_turns', 'thread_turns',
        ['parent_turn_id'], ['id'],
        ondelete='SET NULL'
    )
    
    # 创建索引以提高查询性能
    op.create_index('ix_thread_turns_parent_turn_id', 'thread_turns', ['parent_turn_id'], unique=False)
    
    # 创建索引用于上下文查询
    op.create_index('ix_thread_turns_context_updated', 'thread_turns', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除索引
    op.drop_index('ix_thread_turns_context_updated', table_name='thread_turns')
    op.drop_index('ix_thread_turns_parent_turn_id', table_name='thread_turns')
    
    # 删除外键约束
    op.drop_constraint('fk_thread_turns_parent_turn_id', 'thread_turns', type_='foreignkey')
    
    # 删除字段
    op.drop_column('thread_turns', 'parent_turn_id')
    op.drop_column('thread_turns', 'context_snapshot')
    # ### end Alembic commands ###